AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lab 03 - Orquestacion ETL con Step Functions (Glue sync, paralelo)'

Parameters:
  StudentId:
    Type: String
  Env:
    Type: String
    Default: dev
  StepFunctionsRoleArn:
    Type: String
    Description: 'Output del Lab 00'
  GlueJobName:
    Type: String
    Description: 'Output del Lab 01'

Resources:
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/vendedlogs/states/etl-labs-${StudentId}-${Env}-pipeline'
      RetentionInDays: 14

  EtlPipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub 'etl-labs-${StudentId}-${Env}-pipeline'
      RoleArn: !Ref StepFunctionsRoleArn
      LoggingConfiguration:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
      DefinitionString:
        !Sub |
          {
            "Comment": "ETL pipeline: raw to silver for customers, orders, payments using a single Glue job",
            "StartAt": "RunEntities",
            "States": {
              "RunEntities": {
                "Type": "Parallel",
                "Branches": [
                  {
                    "StartAt": "RunCustomers",
                    "States": {
                      "RunCustomers": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::glue:startJobRun.sync",
                        "Parameters": {
                          "JobName": "${GlueJobName}",
                          "Arguments": {
                            "--INPUT_PREFIX.$": "$.input_prefix",
                            "--OUTPUT_PREFIX.$": "$.output_prefix",
                            "--SOURCE.$": "$.source",
                            "--DT.$": "$.dt",
                            "--ENTITY": "customers"
                          }
                        },
                        "End": true
                      }
                    }
                  },
                  {
                    "StartAt": "RunOrders",
                    "States": {
                      "RunOrders": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::glue:startJobRun.sync",
                        "Parameters": {
                          "JobName": "${GlueJobName}",
                          "Arguments": {
                            "--INPUT_PREFIX.$": "$.input_prefix",
                            "--OUTPUT_PREFIX.$": "$.output_prefix",
                            "--SOURCE.$": "$.source",
                            "--DT.$": "$.dt",
                            "--ENTITY": "orders"
                          }
                        },
                        "End": true
                      }
                    }
                  },
                  {
                    "StartAt": "RunPayments",
                    "States": {
                      "RunPayments": {
                        "Type": "Task",
                        "Resource": "arn:aws:states:::glue:startJobRun.sync",
                        "Parameters": {
                          "JobName": "${GlueJobName}",
                          "Arguments": {
                            "--INPUT_PREFIX.$": "$.input_prefix",
                            "--OUTPUT_PREFIX.$": "$.output_prefix",
                            "--SOURCE.$": "$.source",
                            "--DT.$": "$.dt",
                            "--ENTITY": "payments"
                          }
                        },
                        "End": true
                      }
                    }
                  }
                ],
                "ResultPath": "$.glue_results",
                "End": true
              }
            }
          }

Outputs:
  StateMachineArn:
    Description: 'ARN de la State Machine'
    Value: !Ref EtlPipelineStateMachine
  StateMachineName:
    Description: 'Nombre de la State Machine'
    Value: !GetAtt EtlPipelineStateMachine.Name
