AWSTemplateFormatVersion: "2010-09-09"
Description: Estudiante - Cliente Ligero (usa datos RAW compartidos del workshop)

Parameters:
  StudentId:
    Description: "Identificador unico en minusculas (ej: jemv)"
    Type: String
    MinLength: 2
    MaxLength: 18
    AllowedPattern: "^[a-z0-9]{2,18}$"
    ConstraintDescription: "Usa de 2 a 18 caracteres, solo minusculas y numeros."

Resources:
  TransformedS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub "serverlessanalytics-${StudentId}-${AWS::AccountId}-transformed"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  AthenaS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub "serverlessanalytics-${StudentId}-${AWS::AccountId}-athena"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  MyTransformedBucket:
    Description: "Bucket donde dejaras los datos transformados"
    Value: !Ref TransformedS3Bucket

  MyAthenaBucket:
    Description: "Bucket para resultados de consultas Athena"
    Value: !Ref AthenaS3Bucket

  SharedRawDataPath:
    Description: "Usa esta ruta S3 para tu Glue Crawler"
    Value: !Join ["", ["s3://", !ImportValue Workshop-SharedRawBucket, "/nyc-taxi/"]]

  MyGlueRole:
    Description: "Rol de Glue provisto por el stack base"
    Value: !ImportValue Workshop-GlueRoleName
